import React, { useState, useMemo } from "react";
import jsPDF from "jspdf";
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell
} from "recharts";

/* ================= DATA ================= */
const facultyNames = [
  "Dr. Ramesh Kumar","Dr. Suresh Rao","Dr. Anil Sharma","Dr. Kiran Patel","Dr. Venkatesh Naidu",
  "Dr. Mahesh Reddy","Dr. Sunitha Devi","Dr. Prakash Mehta","Dr. Ravi Teja","Dr. Sumanth Varma",
  "Dr. Lakshmi Narayana","Dr. Harsha Vardhan","Dr. Pooja Singh","Dr. Nikhil Jain","Dr. Aparna Iyer",
  "Dr. Naveen Chandra","Dr. Priya Malhotra","Dr. Arjun Verma","Dr. Sneha Kulkarni","Dr. Rohit Agarwal"
];

const facultyInit = facultyNames.map((name, i) => ({
  id: "T" + (i + 1),
  name,
}));

const ROOMS = Array.from({ length: 20 }, (_, i) => ({
  id: "R" + (i + 1),
  name: "Room " + (101 + i),
  required: i % 5 === 0 ? 3 : 2,
}));

/* ================= COMPONENT ================= */
export default function SmartInvigilatorEngine() {

  const [faculty] = useState(facultyInit);

  const [allocations, setAllocations] = useState(() => {
    const obj = {};
    ROOMS.forEach(r => (obj[r.id] = []));
    return obj;
  });

  const [selectedRoom, setSelectedRoom] = useState(null);

  /* ================= ANALYTICS ================= */
  const facultyStats = useMemo(() => {
    const map = {};
    faculty.forEach(f => map[f.id] = { ...f, today: 0 });

    Object.values(allocations).forEach(list => {
      list.forEach(fid => {
        if (map[fid]) map[fid].today++;
      });
    });

    return Object.values(map).map(f => {
      let risk = "Low";
      if (f.today >= 2) risk = "High";
      else if (f.today === 1) risk = "Medium";
      return { ...f, risk };
    });
  }, [allocations, faculty]);

  const overworked = facultyStats.filter(f => f.risk === "High");
  const balanced = facultyStats.filter(f => f.risk === "Medium");
  const underutilized = facultyStats.filter(f => f.risk === "Low");

  /* ================= SUMMARY ================= */
  const totalRequiredSlots = ROOMS.reduce((s, r) => s + r.required, 0);
  const totalAssigned = Object.values(allocations).reduce((s, l) => s + l.length, 0);
  const remainingDuties = totalRequiredSlots - totalAssigned;

  /* ================= ASSIGN ================= */
  function assignFaculty(roomId, fid) {
    setAllocations(prev => {
      const current = prev[roomId];
      const room = ROOMS.find(r => r.id === roomId);

      if (current.includes(fid)) return prev;

      if (current.length >= room.required) {
        alert("Room already full");
        return prev;
      }

      return { ...prev, [roomId]: [...current, fid] };
    });
  }

  /* ================= PDF ================= */
  function downloadRoomsPDF() {
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("SMART INVIGILATOR SYSTEM", 105, 15, { align: "center" });
    doc.setFontSize(16);
    doc.text("Exam Hall Allocation Report", 105, 25, { align: "center" });
    doc.line(14, 30, 196, 30);

    let y = 40;

    ROOMS.forEach((r, idx) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      doc.setFontSize(13);
      doc.text(`${idx + 1}. ${r.name}`, 14, y); y += 6;
      doc.setFontSize(11);
      doc.text(`Required Invigilators: ${r.required}`, 20, y); y += 6;

      const list = allocations[r.id];

      if (list.length === 0) {
        doc.text("Assigned Faculty: NONE", 20, y); y += 8;
      } else {
        doc.text("Assigned Faculty:", 20, y); y += 6;
        list.forEach((fid, i) => {
          const f = faculty.find(x => x.id === fid);
          doc.text(`   ${i + 1}. ${f.name}`, 24, y);
          y += 6;
        });
        y += 4;
      }

      doc.line(14, y, 196, y);
      y += 6;
    });

    doc.setFontSize(10);
    doc.text("Generated by Smart Invigilator Allocation Engine", 105, 290, { align: "center" });

    doc.save("Exam_Hall_Allocation_Report.pdf");
  }

  function downloadFacultyPDF() {
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("SMART INVIGILATOR SYSTEM", 105, 15, { align: "center" });
    doc.setFontSize(16);
    doc.text("Faculty Workload & Utilization Report", 105, 25, { align: "center" });
    doc.line(14, 30, 196, 30);

    let y = 40;

    doc.setFontSize(13);
    doc.text("Summary:", 14, y); y += 8;

    doc.setFontSize(11);
    doc.text(`Total Faculty: ${faculty.length}`, 20, y); y += 6;
    doc.text(`Total Required Duties: ${totalRequiredSlots}`, 20, y); y += 6;
    doc.text(`Total Assigned Duties: ${totalAssigned}`, 20, y); y += 6;
    doc.text(`Remaining Duties: ${remainingDuties}`, 20, y); y += 10;

    doc.text(`Overloaded Faculty (High): ${overworked.length}`, 20, y); y += 6;
    doc.text(`Balanced Faculty (Medium): ${balanced.length}`, 20, y); y += 6;
    doc.text(`Underutilized Faculty (Low): ${underutilized.length}`, 20, y); y += 10;

    doc.line(14, y, 196, y);
    y += 10;

    doc.setFontSize(13);
    doc.text("Detailed Faculty Workload:", 14, y);
    y += 8;

    facultyStats.forEach((f, idx) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      doc.setFontSize(11);
      doc.text(
        `${idx + 1}. ${f.name}  |  Duties Assigned: ${f.today}  |  Load Level: ${f.risk}`,
        14,
        y
      );
      y += 6;
    });

    doc.setFontSize(10);
    doc.text("Generated by Smart Invigilator Allocation Engine", 105, 290, { align: "center" });

    doc.save("Faculty_Workload_Analysis_Report.pdf");
  }

  /* ================= CHART DATA ================= */
  const barData = facultyStats.map(f => ({
    name: f.name.split(" ")[1] || f.name,
    duties: f.today
  }));

  const pieData = [
    { name: "Underutilized", value: underutilized.length },
    { name: "Balanced", value: balanced.length },
    { name: "Overloaded", value: overworked.length },
  ];

  const PIE_COLORS = ["#22c55e", "#eab308", "#ef4444"];

  /* ================= UI ================= */
  return (
    <div style={{
      background: "radial-gradient(circle at top, #020617, #000)",
      minHeight: "100vh",
      color: "#e5e7eb",
      padding: 30,
      fontFamily: "Poppins, Segoe UI",
    }}>

      <h1 style={{ textAlign: "center", fontSize: 42, marginBottom: 10 }}>
        Smart Invigilator Allocation Engine
      </h1>

      <div style={{ textAlign: "center", marginBottom: 30 }}>
        <button onClick={downloadRoomsPDF} style={{ marginRight: 20 }}>📄 Exam Halls PDF</button>
        <button onClick={downloadFacultyPDF}>📊 Faculty Analysis PDF</button>
      </div>

      {/* KPI */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 20, marginBottom: 30 }}>
        {[
          ["Total Faculty", faculty.length],
          ["Total Rooms", ROOMS.length],
          ["Remaining Duties", remainingDuties],
          ["Assigned Duties", totalAssigned],
        ].map(([title, value]) => (
          <div key={title} style={{
            background: "linear-gradient(135deg,#0f172a,#020617)",
            padding: 20, borderRadius: 16, textAlign: "center"
          }}>
            <div style={{ fontSize: 13, color: "#94a3b8", marginBottom: 8 }}>{title}</div>
            <div style={{
              fontSize: 40,
              fontWeight: 900,
              background: "linear-gradient(90deg,#38bdf8,#22d3ee)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent"
            }}>{value}</div>
          </div>
        ))}
      </div>

      {/* CHARTS */}
      <div style={{ display: "flex", gap: 30, marginBottom: 40 }}>
        <div style={{ flex: 1, background: "#04102f", padding: 20, borderRadius: 16 }}>
        <h3 style={{
  textAlign: "center",
  fontSize: "42px",
  fontWeight: "900",
  letterSpacing: "1.5px",
  marginBottom: "15px",
  background: "linear-gradient(90deg, #38bdf8, #22d3ee, #a5f3fc)",
  WebkitBackgroundClip: "text",
  WebkitTextFillColor: "transparent",
  textShadow: "0 0 20px rgba(56,189,248,0.6)"
}}>
  📊 Faculty Workload Analysis
</h3>

          <ResponsiveContainer width="100%" height={380}>
            <BarChart data={barData}>
              <XAxis dataKey="name" hide />
              <YAxis />
              <Tooltip />
              <Bar dataKey="duties" fill="#38bdf8" />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div style={{ flex: 1, background: "#0f172a", padding: 20, borderRadius: 16 }}>
          <h3 style={{ textAlign: "center", color: "#7dd3fc" }}>Faculty Utilization</h3>
          <ResponsiveContainer width="100%" height={380}>
            <PieChart>
              <Pie data={pieData} dataKey="value" cx="50%" cy="50%" outerRadius={180} label>
                {pieData.map((_, i) => <Cell key={i} fill={PIE_COLORS[i]} />)}
              </Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* ROOMS */}
      <h2 style={{ textAlign: "center", fontSize: 70, marginBottom: 20 }}>🏫 Exam Halls</h2>

      <div style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill,minmax(560px,10fr))",
        gap: 20
      }}>
        {ROOMS.map(r => {
          const filled = allocations[r.id].length;
          const color =
            filled === r.required ? "#16a34a" :
            filled === 0 ? "#0ea5e9" : "#facc15";

          return (
            <div
              key={r.id}
              onClick={() => setSelectedRoom(r)}
              style={{
                background: `linear-gradient(135deg,${color},#020617)`,
                minHeight: 140,
                borderRadius: 18,
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                cursor: "pointer"
              }}
            >
              <div style={{ fontSize: 28, fontWeight: 900 }}>{r.name}</div>
              <div style={{ marginTop: 10, padding: "6px 16px", borderRadius: 20, background: "#020617" }}>
                {filled} / {r.required} Assigned
              </div>
            </div>
          );
        })}
      </div>

      {/* MODAL */}
      {selectedRoom && (
        <div style={{
          position: "fixed", inset: 0, background: "rgba(0,0,0,.7)",
          display: "flex", justifyContent: "center", alignItems: "center"
        }}>
          <div style={{
            background: "#020617",
            padding: 24,
            borderRadius: 18,
            width: 900,
            maxWidth: "95vw"
          }}>
            <h2>{selectedRoom.name}</h2>

            <div style={{ maxHeight: 500, overflowY: "auto", paddingRight: 10 }}>
              {facultyStats.map(f => (
                <div key={f.id} style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  background: "#0f172a",
                  fontSize: 22,
                  padding: 14,
                  borderRadius: 12,
                  marginBottom: 10
                }}>
                  <span>{f.name}</span>
                  <span style={{
                    padding: "6px 14px",
                    borderRadius: 20,
                    background:
                      f.risk === "High" ? "#7f1d1d" :
                      f.risk === "Medium" ? "#78350f" : "#14532d"
                  }}>{f.risk}</span>
                  <button onClick={() => assignFaculty(selectedRoom.id, f.id)}>Assign</button>
                </div>
              ))}
            </div>

            <div style={{ textAlign: "right", marginTop: 12 }}>
              <button onClick={() => setSelectedRoom(null)}>Close</button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
