import React, { useEffect, useMemo, useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import jsPDF from "jspdf";


/* ---------------- NAAC Criteria ---------------- */

const CRITERIA = [
  { id: "C1", title: "Curricular Aspects" },
  { id: "C2", title: "Teaching – Learning & Evaluation" },
  { id: "C3", title: "Research, Innovations & Extension" },
  { id: "C4", title: "Infrastructure & Learning Resources" },
  { id: "C5", title: "Student Support & Progression" },
  { id: "C6", title: "Governance, Leadership & Management" },
  { id: "C7", title: "Institutional Values & Best Practices" }
];

const emptyCriteria = () => ({
  narrative: "",
  evidences: [],
  metrics: [{ key: "", value: "" }],
  status: "Draft",
  lastSaved: null
});

/* ---------------- Component ---------------- */

export default function SSR() {

  const navigate = useNavigate();

  const [active, setActive] = useState("C1");
  const [store, setStore] = useState({});
  const [saving, setSaving] = useState(false);

  /* Load stored SSR data */
  useEffect(() => {
    const raw = localStorage.getItem("vistar-ssr");
    if (raw) setStore(JSON.parse(raw));
  }, []);

  const data = store[active] || emptyCriteria();

  /* ---------- helpers ---------- */

  function updateCurrent(patch) {
    setStore((prev) => ({
      ...prev,
      [active]: { ...data, ...patch }
    }));
  }

  function save() {

    setSaving(true);

    const updated = {
      ...store,
      [active]: { ...data, lastSaved: new Date().toISOString() }
    };

    localStorage.setItem("vistar-ssr", JSON.stringify(updated));
    setStore(updated);

    setTimeout(() => setSaving(false), 600);
  }

  function addEvidence() {
    const url = prompt("Paste evidence / document link");
    if (!url) return;
    updateCurrent({ evidences: [...data.evidences, url] });
  }

  function removeEvidence(i) {
    const next = [...data.evidences];
    next.splice(i, 1);
    updateCurrent({ evidences: next });
  }

  function updateMetric(i, field, value) {
    const next = data.metrics.map((m, idx) =>
      idx === i ? { ...m, [field]: value } : m
    );
    updateCurrent({ metrics: next });
  }

  function addMetric() {
    updateCurrent({
      metrics: [...data.metrics, { key: "", value: "" }]
    });
  }

  function removeMetric(i) {
    const next = [...data.metrics];
    next.splice(i, 1);
    updateCurrent({ metrics: next });
  }

  function handleBack() {
    navigate(-1);
  }

  /* ---------- compliance & progress ---------- */

  const compliance = useMemo(() => {

    const prepared = data.narrative.trim().length > 50;
    const documents = data.evidences.length > 0;
    const metrics = data.metrics.some(
      (m) => m.key && m.value
    );

    return { prepared, documents, metrics };

  }, [data]);

  const completion = useMemo(() => {

    const c = [
      compliance.prepared,
      compliance.documents,
      compliance.metrics
    ].filter(Boolean).length;

    return Math.round((c / 3) * 100);

  }, [compliance]);

  /* ---------------- PDF REPORT GENERATOR ---------------- */

  function downloadPDF() {

    const pdf = new jsPDF("p", "mm", "a4");

    let y = 15;

    pdf.setFontSize(16);
    pdf.text("Self Study Report (SSR)", 105, y, { align: "center" });

    y += 7;

    pdf.setFontSize(11);
    pdf.text("Generated by Vistar Netra", 105, y, { align: "center" });

    y += 10;

    CRITERIA.forEach((c) => {

      const section = store[c.id] || emptyCriteria();

      if (y > 260) {
        pdf.addPage();
        y = 15;
      }

      pdf.setFontSize(13);
      pdf.text(`${c.id} – ${c.title}`, 10, y);
      y += 6;

      pdf.setFontSize(10);

      /* Narrative */
      pdf.text("Narrative:", 10, y);
      y += 5;

      const narrative =
        section.narrative && section.narrative.trim()
          ? section.narrative
          : "Not provided";

      const narrativeLines = pdf.splitTextToSize(narrative, 180);
      pdf.text(narrativeLines, 10, y);
      y += narrativeLines.length * 5 + 3;

      /* Evidences */
      pdf.text("Evidences:", 10, y);
      y += 5;

      if (section.evidences.length === 0) {
        pdf.text("- No evidences added", 12, y);
        y += 5;
      } else {
        section.evidences.forEach((e, i) => {
          const evLines = pdf.splitTextToSize(
            `${i + 1}. ${e}`, 176
          );
          pdf.text(evLines, 12, y);
          y += evLines.length * 5;
        });
      }

      y += 3;

      /* Metrics */
      pdf.text("Metrics / Quantitative Indicators:", 10, y);
      y += 5;

      const validMetrics = section.metrics.filter(
        (m) => m.key && m.value
      );

      if (validMetrics.length === 0) {
        pdf.text("- No metrics provided", 12, y);
        y += 5;
      } else {
        validMetrics.forEach((m, i) => {
          pdf.text(
            `${i + 1}. ${m.key} : ${m.value}`,
            12,
            y
          );
          y += 5;
        });
      }

      y += 3;

      /* Status */
      pdf.text(`Status : ${section.status}`, 10, y);
      y += 5;

      /* Compliance */
      const prepared =
        section.narrative.trim().length > 50;
      const documents =
        section.evidences.length > 0;
      const metricsOk =
        section.metrics.some((m) => m.key && m.value);

      pdf.text(
        `Prepared: ${prepared ? "Yes" : "No"} | Documents: ${documents ? "Yes" : "No"} | Metrics: ${metricsOk ? "Yes" : "No"}`,
        10,
        y
      );

      y += 10;

      pdf.setDrawColor(180);
      pdf.line(10, y, 200, y);
      y += 6;

    });

    pdf.save("SSR-Complete-Report.pdf");
  }

  /* ---------------- UI ---------------- */

  return (
    <div className="naac-dashboard min-h-screen p-6">

      {/* Header */}
      <div className="mb-6 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold">
            Self Study Reports (SSR)
          </h1>
          <p className="text-sm mt-1">
            Criteria wise NAAC report preparation & compliance tracking
          </p>
        </div>

        <div className="flex gap-3">
          <button
            onClick={handleBack}
            className="rounded-xl border px-4 py-2 text-sm font-semibold"
          >
            ← Back
          </button>

          <Link
            to="/quality"
            className="rounded-xl border px-4 py-2 text-sm font-semibold"
          >
            Quality Home
          </Link>
        </div>
      </div>

      {/* Completion bar */}
      <div className="rounded-2xl p-4 mb-6">
        <div className="flex items-center justify-between mb-2">
          <span className="font-semibold">
            {active} Completion
          </span>
          <span className="text-sm">
            {completion}%
          </span>
        </div>

        <div className="w-full h-2 rounded-full bg-slate-800 overflow-hidden">
          <div
            className="h-full"
            style={{
              width: `${completion}%`,
              background:
                "linear-gradient(90deg,#6366f1,#8b5cf6)"
            }}
          />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">

        {/* Criteria list */}
        <div className="rounded-2xl p-4">
          <h3 className="text-lg font-semibold mb-3">
            Criteria
          </h3>
          <ul className="space-y-2">
            {CRITERIA.map((c) => (
              <li
                key={c.id}
                onClick={() => setActive(c.id)}
                className={`cursor-pointer rounded-lg px-3 py-2 border ${
                  active === c.id
                    ? "border-indigo-500"
                    : "border-slate-700"
                }`}
              >
                <strong>{c.id}</strong> – {c.title}
              </li>
            ))}
          </ul>
        </div>

        {/* Main panel */}
        <div className="lg:col-span-3 space-y-6">

          {/* Narrative */}
          <div className="rounded-2xl p-5">
            <div className="flex items-center justify-between mb-2">
              <h2 className="text-xl font-semibold">
                {active} Narrative
              </h2>
              <span className="text-sm">
                Status : {data.status}
              </span>
            </div>

            <textarea
              className="w-full min-h-[180px] rounded-lg p-3"
              placeholder="Write official NAAC narrative here..."
              value={data.narrative}
              onChange={(e) =>
                updateCurrent({
                  narrative: e.target.value
                })
              }
            />

            <div className="flex items-center justify-between mt-2 text-sm">
              <span>
                Words :{" "}
                {
                  data.narrative
                    .trim()
                    .split(/\s+/)
                    .filter(Boolean).length
                }
              </span>
              <span>
                Last saved :{" "}
                {data.lastSaved
                  ? new Date(
                      data.lastSaved
                    ).toLocaleString()
                  : "-"}
              </span>
            </div>
          </div>

          {/* Evidence */}
          <div className="rounded-2xl p-5">
            <div className="flex justify-between items-center mb-3">
              <h2 className="text-xl font-semibold">
                Evidence Mapping
              </h2>
              <button
                onClick={addEvidence}
                className="px-3 py-1 rounded-lg border"
              >
                Add
              </button>
            </div>

            <ul className="space-y-2 text-sm">
              {data.evidences.map((e, i) => (
                <li
                  key={i}
                  className="flex justify-between items-center rounded-lg px-3 py-2 border"
                >
                  <a
                    href={e}
                    target="_blank"
                    rel="noreferrer"
                  >
                    {e}
                  </a>
                  <button
                    onClick={() =>
                      removeEvidence(i)
                    }
                  >
                    Remove
                  </button>
                </li>
              ))}

              {!data.evidences.length && (
                <p>No evidences added</p>
              )}
            </ul>
          </div>

          {/* Metrics */}
          <div className="rounded-2xl p-5">
            <div className="flex justify-between items-center mb-3">
              <h2 className="text-xl font-semibold">
                Metrics / Quantitative Indicators
              </h2>
              <button
                onClick={addMetric}
                className="px-3 py-1 rounded-lg border"
              >
                Add row
              </button>
            </div>

            <div className="space-y-2">
              {data.metrics.map((m, i) => (
                <div
                  key={i}
                  className="grid grid-cols-5 gap-2"
                >
                  <input
                    className="col-span-3 rounded-lg px-2 py-1"
                    placeholder="Metric name"
                    value={m.key}
                    onChange={(e) =>
                      updateMetric(
                        i,
                        "key",
                        e.target.value
                      )
                    }
                  />

                  <input
                    className="col-span-1 rounded-lg px-2 py-1"
                    placeholder="Value"
                    value={m.value}
                    onChange={(e) =>
                      updateMetric(
                        i,
                        "value",
                        e.target.value
                      )
                    }
                  />

                  <button
                    onClick={() =>
                      removeMetric(i)
                    }
                  >
                    X
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* Submission */}
          <div className="rounded-2xl p-5">
            <h2 className="text-xl font-semibold mb-3">
              Submission & Compliance
            </h2>

            <div className="flex items-center gap-4 mb-3">
              <label>Status</label>
              <select
                className="rounded-lg px-3 py-1"
                value={data.status}
                onChange={(e) =>
                  updateCurrent({
                    status: e.target.value
                  })
                }
              >
                <option>Draft</option>
                <option>Submitted</option>
                <option>Locked</option>
              </select>
            </div>

            <div className="text-sm mb-4">
              Prepared :{" "}
              {compliance.prepared ? "✔" : "✖"} | Documents :{" "}
              {compliance.documents ? "✔" : "✖"} | Metrics :{" "}
              {compliance.metrics ? "✔" : "✖"}
            </div>

            <div className="flex gap-3">
              <button
                onClick={save}
                className="px-5 py-2 rounded-xl border font-semibold"
              >
                {saving
                  ? "Saving..."
                  : "Save Report"}
              </button>

              <button
                onClick={downloadPDF}
                className="px-5 py-2 rounded-xl border font-semibold"
              >
                Download Full Report PDF
              </button>
            </div>
          </div>

        </div>

      </div>

    </div>
  );
}



